name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install client deps
        working-directory: ./client
        run: npm ci
      - name: Build client
        working-directory: ./client
        run: npm run build

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install server deps
        working-directory: ./server
        run: npm ci
      - name: Typecheck server
        working-directory: ./server
        run: npm run build --if-present || true
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: senvia
          POSTGRES_PASSWORD: senvia123
          POSTGRES_DB: senvia_niryat
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd server
          npm install
      - name: Build
        run: |
          cd server
          npm run build
      - name: Run tests
        run: |
          cd server
          npm test
